---

root: true

plugins:
  - jest
  - functional
  - testing-library
  - jest-dom

env:
  jest: true
  browser: true
  es2020: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:testing-library/dom'
  - "plugin:jest-dom/recommended"

parserOptions:
  ecmaVersion: 2020

rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-param-reassign: 0
